"""Mensa provider registry."""

from __future__ import annotations

from typing import Dict

from mensa_cli.providers.stw_berlin import parser as stw_parser
from mensa_cli.providers.types import MensaSite

SITES: Dict[str, MensaSite] = {
    "ash_berlin": MensaSite(
        key="ash_berlin",
        name="Mensa ASH Berlin",
        url="https://www.stw.berlin/mensen/einrichtungen/mensa-ash-berlin.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "bht_luxemburger_strasse": MensaSite(
        key="bht_luxemburger_strasse",
        name="Mensa BHT Luxemburger Straße",
        url="https://www.stw.berlin/mensen/einrichtungen/berliner-hochschule-für-technik/mensa-bht.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "charite_zahnklinik": MensaSite(
        key="charite_zahnklinik",
        name="Mensa Charité Zahnklinik",
        url="https://www.stw.berlin/mensen/einrichtungen/charité/mensa-charité-zahnklinik.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "ehb_teltower_damm": MensaSite(
        key="ehb_teltower_damm",
        name="Mensa EHB Teltower Damm",
        url="https://www.stw.berlin/mensen/einrichtungen/ehb/mensa-ehb-teltower-damm.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "fu_herrenhaus_düppel": MensaSite(
        key="fu_herrenhaus_düppel",
        name="Mensa FU Herrenhaus Düppel",
        url="https://www.stw.berlin/mensen/einrichtungen/freie-universität-berlin/mensa-fu-herrenhaus-düppel.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "fu_i_shokudo": MensaSite(
        key="fu_i_shokudo",
        name="Mensa FU I Shokudō",
        url="https://www.stw.berlin/mensen/einrichtungen/freie-universität-berlin/shokudo.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "fu_ii": MensaSite(
        key="fu_ii",
        name="Mensa FU II",
        url="https://www.stw.berlin/mensen/einrichtungen/freie-universität-berlin/mensa-fu-ii.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "fu_koserstraße": MensaSite(
        key="fu_koserstraße",
        name="Mensa FU Koserstraße",
        url="https://www.stw.berlin/mensen/einrichtungen/freie-universität-berlin/mensa-fu-koserstraße.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "fu_lankwitz_malteserstraße": MensaSite(
        key="fu_lankwitz_malteserstraße",
        name="Mensa FU Lankwitz Malteserstraße",
        url="https://www.stw.berlin/mensen/einrichtungen/freie-universität-berlin/mensa-fu-lankwitz.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "fu_pharmazie": MensaSite(
        key="fu_pharmazie",
        name="Mensa FU Pharmazie",
        url="https://www.stw.berlin/mensen/einrichtungen/freie-universität-berlin/mensa-fu-pharmazie.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "hfs_ernst_busch": MensaSite(
        key="hfs_ernst_busch",
        name="Mensa HfS Ernst Busch",
        url="https://www.stw.berlin/mensen/einrichtungen/mensa-hfs-ernst-busch.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "htw_treskowallee": MensaSite(
        key="htw_treskowallee",
        name="Mensa HTW Treskowallee",
        url="https://www.stw.berlin/mensen/einrichtungen/hochschule-für-technik-und-wirtschaft-berlin/mensa-htw-treskowallee.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "htw_wilhelminenhof": MensaSite(
        key="htw_wilhelminenhof",
        name="Mensa HTW Wilhelminenhof",
        url="https://www.stw.berlin/mensen/einrichtungen/hochschule-für-technik-und-wirtschaft-berlin/mensa-htw-wilhelminenhof.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "hu_nord": MensaSite(
        key="hu_nord",
        name="Mensa HU Nord",
        url="https://www.stw.berlin/mensen/einrichtungen/humboldt-universität-zu-berlin/mensa-hu-nord.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "hu_oase_adlershof": MensaSite(
        key="hu_oase_adlershof",
        name="Mensa HU Oase Adlershof",
        url="https://www.stw.berlin/mensen/einrichtungen/humboldt-universität-zu-berlin/mensa-hu-oase-adlershof.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "hu_süd": MensaSite(
        key="hu_süd",
        name="Mensa HU Süd",
        url="https://www.stw.berlin/mensen/einrichtungen/humboldt-universität-zu-berlin/mensa-hu-süd.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "hwr_badensche_straße": MensaSite(
        key="hwr_badensche_straße",
        name="Mensa HWR Badensche Straße",
        url="https://www.stw.berlin/mensen/einrichtungen/hwr/mensa-hwr-badensche-straße.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "khs_weissensee": MensaSite(
        key="khs_weissensee",
        name="Mensa KHS Weißensee",
        url="https://www.stw.berlin/mensen/einrichtungen/mensa-khs-weissensee.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "khsb": MensaSite(
        key="khsb",
        name="Mensa KHSB",
        url="https://www.stw.berlin/mensen/einrichtungen/mensa-khsb.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "tu_hardenbergstraße": MensaSite(
        key="tu_hardenbergstraße",
        name="Mensa TU Hardenbergstraße",
        url="https://www.stw.berlin/mensen/einrichtungen/technische-universität-berlin/mensa-tu-/udk-hardenbergstraße.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "tu_marchstraße": MensaSite(
        key="tu_marchstraße",
        name="Mensa TU Marchstraße",
        url="https://www.stw.berlin/mensen/einrichtungen/technische-universität-berlin/mensa-tu-marchstraße.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
    "tu_veggie2_0": MensaSite(
        key="tu_veggie2_0",
        name="Mensa TU Veggie 2.0",
        url="https://www.stw.berlin/mensen/einrichtungen/technische-universität-berlin/veggie2.0.html",
        provider="stw_berlin",
        city="Berlin",
        parser=stw_parser.parse_menu,
    ),
}
